// <auto-generated />
namespace JurassicBark.UI.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FName));
        
        string IMigrationMetadata.Id
        {
            get { return "201808171724341_FName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
