//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JurassicBark.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeNote
    {
        public int NoteID { get; set; }
        public int PetID { get; set; }
        public string EmployeeID { get; set; }
        public string Note { get; set; }
        public System.DateTime NoteDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
